### ISSUE TITLE
Stories

### ISSUE THREAD

**Issue by JeromeLev141** [Floppa-equipe-16/floppa#62]
# Stories

Maintenant que la majorité des features sont complétées, l'équipe de Floppa désire récolter des idées pour le développement futur de la plateforme. Elle vous demande donc de fournir **4 stories** originales qui permettront de surpasser la compétition.

Voici quelques critères à respecter :

- Respecter les critères, le format et le contenu d'une story (voir le cours et les labs)
- **Ne pas impliquer une modification des routes actuelles (requête, réponse, url, etc.)**
- **Ne pas être en lien avec l'acceptation/sélection des offres** (TP4)
- Chaque issue doit avoir une liste de critères de succès permettant au PO/client de tester la fonctionalité

Voici des exemples qui n'offrent **pas** assez de valeur :

- Obtenir tous les vendeurs
- Supprimer ou modifier un vendeur, un produit ou une offre

**Comment by AnthonySirois** [comment]
Idées
- Historique des achats
