### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by JeromeLev141** [Floppa-equipe-16/floppa#68]
# Architecture

Refaites l'exercice sur le diagramme d'architecture du TP2. Par contre, au lieu de justifier vos décisions et d'identifier des problèmes, montrez 3 problèmes que vous avez réglé et expliquez comment vous vous y êtes pris. Insérez votre diagramme ainsi que vos réponses dans le document d'exercice.

**Comment by AnthonySirois** [comment]
- Déplacer la configuration du ResourceConfig du main dans un autre classe
