### ISSUE TITLE
Analyse de formattage

### ISSUE THREAD

**Issue by JeromeLev141** [Floppa-equipe-16/floppa#9]
## Analyse de formattage

Vous devez installer un plugin Maven permettant d'analyser le formattage de votre code. Vous devez **fournir la commande** (_goal_ Maven) permettant d'effectuer la vérification dans le fichier d'exercice. Votre plugin peut également offrir la possibilité de faire du formattage automatique. Dans tous les cas, assurez-vous que le code remis soit bien formatté selon votre outil! Vous devrez également l'adapter à votre projet, c'est-à-dire le configurer selon votre style voulu et seulement pour les fichiers désirés (ex: pas besoin de configuration pour les fichiers OCaml...).

Voici quelques exemples d'outils offerts sur Maven :

- Checkstyle
- Spotless
- Prettier
- EditorConfig

Vous êtes invités à essayer et comparer les différents outils afin de choisir celui qui vous convient le mieux.

**Comment by alexprudhomme** [comment]
Add Spotless with googleJavaFormat on develop branch.

To use : mvn spotless:apply
