### ISSUE TITLE
Obtention classement des vendeurs

### ISSUE THREAD

**Issue by JeromeLev141** [Floppa-equipe-16/floppa#94]
# Obtention classement des vendeurs

## Description

En tant qu'utilisateur, je peux consulter les meilleurs vendeurs avec leurs scores respectifs

## Critères de succès

- Je vois les informations de base du vendeur.
- Je vois le score du vendeur.
- Je vois les vendeurs classés par score décroissant.
- Je vois le nombre de vendeurs demandé.

### Requête

**Route**

`GET /sellers`

**Query params**

- `top` (`int`) : Le nombre de vendeurs désirés dans la classement, de 1 à 'top'

### Réponse

**Status**

`200 OK`

**Body**

```ts
{
  sellers: [
    {
      id: string,
      createdAt: DateTime,
      name: string,
      birthdate: Date,
      email: Email,
      phoneNumber: PhoneNumber,
      bio: string,
      score: Amount,
      productsStats: {
        count: number,
        avgAmount: Amount | null
      }
    }
  ]
}
```

**Exemple**

```json
{
  "sellers": [
    {
      "id": "abc",
      "createdAt": "2020-06-04T06:56:34.918Z",
      "name": "John Doe",
      "birthdate": "1968-09-12",
      "email": "john.doe123@gmail.com",
      "phoneNumber": "14181234567",
      "bio": "A simpe man",
      "score": 97
      "productsStats": {
        "count": 4,
        "avgAmount": 24.75
      }
    }
  ]
}
```

### Exceptions

- `INVALID_PARAMETER` si le Query param 'top' est invalide.

**Comment by AnthonySirois** [comment]
- Score = prix de tous les produits que le vendeur à vendu
- products = Comprends l'information de tous les produits (et non seulement ceux vendu)
